# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myPuzzle.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1130, 608)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_num = QtWidgets.QSpinBox(Dialog)
        self.spinBox_num.setToolTipDuration(-1)
        self.spinBox_num.setMinimum(1)
        self.spinBox_num.setMaximum(7)
        self.spinBox_num.setObjectName("spinBox_num")
        self.horizontalLayout.addWidget(self.spinBox_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.show_originalPic = QtWidgets.QPushButton(Dialog)
        self.show_originalPic.setObjectName("show_originalPic")
        self.gridLayout.addWidget(self.show_originalPic, 0, 0, 1, 1)
        self.selfChoose = QtWidgets.QPushButton(Dialog)
        self.selfChoose.setObjectName("selfChoose")
        self.gridLayout.addWidget(self.selfChoose, 2, 0, 1, 1)
        self.try_newPic = QtWidgets.QPushButton(Dialog)
        self.try_newPic.setObjectName("try_newPic")
        self.gridLayout.addWidget(self.try_newPic, 0, 1, 1, 1)
        self.recompose = QtWidgets.QPushButton(Dialog)
        self.recompose.setObjectName("recompose")
        self.gridLayout.addWidget(self.recompose, 1, 0, 1, 1)
        self.challengeMode = QtWidgets.QPushButton(Dialog)
        self.challengeMode.setObjectName("challengeMode")
        self.gridLayout.addWidget(self.challengeMode, 1, 1, 1, 1)
        self.help = QtWidgets.QPushButton(Dialog)
        self.help.setObjectName("help")
        self.gridLayout.addWidget(self.help, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.timeCounter = QtWidgets.QLCDNumber(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeCounter.sizePolicy().hasHeightForWidth())
        self.timeCounter.setSizePolicy(sizePolicy)
        self.timeCounter.setMaximumSize(QtCore.QSize(16777215, 100))
        self.timeCounter.setProperty("value", 30.0)
        self.timeCounter.setObjectName("timeCounter")
        self.verticalLayout_3.addWidget(self.timeCounter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PuzzleGame"))
        self.label.setText(_translate("Dialog", "拼图大小(n×n)"))
        self.show_originalPic.setText(_translate("Dialog", "查看原图"))
        self.selfChoose.setText(_translate("Dialog", "自选图片"))
        self.try_newPic.setText(_translate("Dialog", "试玩新图"))
        self.recompose.setText(_translate("Dialog", "打乱图片"))
        self.challengeMode.setText(_translate("Dialog", "挑战模式"))
        self.help.setText(_translate("Dialog", "游戏说明"))
